server:
  port: 7000
  error:
    include-message: always

app:
  product-service:
    port: 7001
  recommendation-service:
    port: 7003
  review-service:
    port: 7002

logging:
  level:
    root: INFO
    com.learning: DEBUG
