server:
  port: 7000
  error:
    include-message: always

app:
  product-service:
    port: 7001
    host: localhost
  recommendation-service:
    port: 7003
    host: localhost
  review-service:
    port: 7002
    host: localhost

logging:
  level:
    root: INFO
    com.learning: DEBUG
